import { generateCode, generateUsageSnippet } from "./codegen"
import type { CodegenInput, ComponentKind, Platform } from "./types"
import {
  type ProjectProfile,
  frameworkLabel,
  getFileStructure,
  getInstallCommand,
} from "./project-profile"

export interface GlassPromptInput {
  codegen: CodegenInput
  profile: ProjectProfile
  shareUrl?: string
  presetName?: string
}

const COMPONENT_LABELS: Record<ComponentKind, string> = {
  "glass-card": "GlassCard",
  "glass-button": "GlassButton",
  "glass-input": "GlassInput",
  "glass-modal": "GlassModal",
  "glass-tabbar": "GlassTabBar",
  "glass-switch": "GlassSwitch",
  "glass-navbar": "GlassNavigationBar",
}

function componentFileName(kind: ComponentKind): string {
  return kind.replace("glass-", "glass-")
}

function getGlassRules(component: ComponentKind): string {
  const base = `**Glassmorphism rules (all Glass UI primitives)**
- Use \`backdrop-blur-*\` on the glass surface; never rely on opacity alone.
- \`intensity\` maps to background alpha (subtle / medium / strong compound variants).
- \`border\` subtle = 1px hairline; strong = 2px — always semi-transparent white.
- \`tint\` adds a colored wash (blue, pink, orange, teal) at low opacity.
- Prefer \`rounded-2xl\` or \`rounded-3xl\` for iOS-like cards; \`full\` for pills and tab bars.
- Test over busy wallpapers — glass must remain readable (WCAG contrast on text).`

  const specific: Partial<Record<ComponentKind, string>> = {
    "glass-switch": `**GlassSwitch**
- Wrap a native switch or Radix Switch; apply glass track + thumb via CVA.
- Minimum touch target 44×44px; include \`aria-checked\` and keyboard focus ring.`,
    "glass-navbar": `**GlassNavigationBar**
- Top safe-area padding on iOS; sticky with backdrop blur.
- Title centered or leading; action buttons as glass icon buttons.`,
    "glass-tabbar": `**GlassTabBar**
- Fixed bottom bar; equal-width tab items; active state via color + optional scale.`,
    "glass-modal": `**GlassModal**
- Overlay scrim behind card; trap focus; close on Escape.`,
  }
  return `${base}\n\n${specific[component] ?? ""}`.trim()
}

function acceptanceCriteria(platform: Platform, profile: ProjectProfile): string {
  const lines = [
    "- [ ] Project builds without TypeScript errors",
    "- [ ] Glass surface shows blur over non-solid background (Safari + Chrome)",
    "- [ ] Props from this spec match the playground preview",
    profile.hasCnHelper
      ? "- [ ] Reuse existing `cn()` from `@/lib/utils` — do NOT duplicate the helper"
      : "- [ ] Add `cn()` helper (clsx + tailwind-merge) once in `lib/utils.ts`",
    profile.usesShadcn
      ? "- [ ] Place file under shadcn `components/ui/` path; do not conflict with existing primitives"
      : "- [ ] File path matches project convention",
  ]
  if (platform === "native") {
    lines.push("- [ ] NativeWind configured; `className` works on View/Switch")
  } else if (profile.tailwindVersion === "4") {
    lines.push("- [ ] Tailwind v4: `@import 'tailwindcss'` in globals.css")
  }
  return lines.join("\n")
}

export function generateGlassPrompt(input: GlassPromptInput): string {
  const { codegen, profile, shareUrl, presetName } = input
  const { component, mode, platform, options } = codegen
  const label = COMPONENT_LABELS[component]
  const file = componentFileName(component)
  const code = generateCode(codegen)
  const usage = generateUsageSnippet(codegen)
  const modeLabel = mode === "inline" ? "Inline snippet" : "Reusable CVA component"
  const platformLabel = platform === "web" ? "React Web (Tailwind CSS)" : "React Native (NativeWind)"

  const propsTable = `| Property | Value |
|----------|-------|
| theme | \`${options.theme}\` |
| blur | \`${options.blur}\` |
| rounded | \`${options.rounded}\` |
| intensity | \`${options.intensity}\` |
| border | \`${options.border}\` |
| padding | \`${options.padding}\` |
| shadow | \`${options.shadow}\` |
| tint | \`${options.tint}\` |`

  const presetRow = presetName ? `| Preset | ${presetName} |\n` : ""
  const shareRow = shareUrl ? `| Design link | ${shareUrl} |\n` : ""

  return `# GLASS.md — ${label}

> Generated by [Glass UI](https://github.com/lemuayala/glass-ui). Paste this file into Cursor, Claude Code, or any AI coding agent to integrate the component correctly.

---

## 1. Meta

| Field | Value |
|-------|-------|
| Component | **${label}** (\`${component}\`) |
| Platform | ${platformLabel} |
| Export mode | ${modeLabel} |
| Target stack | ${frameworkLabel(profile.framework)} |
| Tailwind | v${profile.tailwindVersion} |
| Component path | \`${profile.componentPath}/${file}.tsx\` |
${presetRow}${shareRow}
---

## 2. Design specification

${propsTable}
${options.text ? `\n**Sample text:** \`${options.text}\`\n` : ""}

---

## 3. Glass rules

${getGlassRules(component)}

---

## 4. Generated code

\`\`\`tsx
${code.trim()}
\`\`\`

---

## 5. Usage

\`\`\`tsx
${usage.trim()}
\`\`\`

---

## 6. Project integration

**Install dependencies** (skip packages already present):

\`\`\`bash
${getInstallCommand(profile, platform)}
\`\`\`

**Suggested file structure:**

${getFileStructure(profile, file)}

**Integration steps:**
1. Create \`${profile.componentPath}/${file}.tsx\` with the code in §4 (or paste inline snippet from §4 into your page).
2. ${mode === "reusable" ? "Import and use as shown in §5." : "No separate import file — inline mode only."}
3. Ensure parent has a non-flat background so \`backdrop-blur\` is visible.
4. Match app theme: component theme is \`${options.theme}\`; wrap or override if your app theme differs.

---

## 7. Acceptance criteria

${acceptanceCriteria(platform, profile)}

---

## 8. Do not

- Do not remove \`backdrop-blur\` or replace glass with flat solid fills.
- Do not use arbitrary Tailwind values outside the design system unless the user asks.
- Do not change prop names — they match the Glass UI playground API.
`
}

export function generateShortGlassPrompt(input: GlassPromptInput): string {
  const { codegen, profile } = input
  const { component, mode, platform, options } = codegen
  const label = COMPONENT_LABELS[component]
  return `Integrate ${label} (${mode}, ${platform}) into my ${frameworkLabel(profile.framework)} project at \`${profile.componentPath}\`. Glass props: theme=${options.theme}, blur=${options.blur}, rounded=${options.rounded}, intensity=${options.intensity}, border=${options.border}, padding=${options.padding}, shadow=${options.shadow}, tint=${options.tint}. Use CVA + tailwind-merge${profile.hasCnHelper ? "; reuse existing cn()" : ""}. Tailwind v${profile.tailwindVersion}. Follow GLASS.md rules: backdrop-blur, compound intensity variants, iOS-like borders. Deliver the component file and one usage example that compiles.`
}
